# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
markdown:            kramdown
#relative_permalinks: true

# Setup
title:               Ioannis Galatos
tagline:             'Blog about Electronics, IoT and Blockchain'
description:         'Bits and Bytes'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ioannis Galatos
  url:               https://twitter.com/mdo
  email:             ionsgltos@gmail.com
  gravatar_md5:      4687d7b35ae880160548537d987018ee
  github:	     ionsgltos
  linkedin:          ioannisgalatos

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"
